trigger:
  branches:
    include:
      - main  # Adjust to your default branch

pool:
  vmImage: ubuntu-latest
#  name: <selfhostone>

#system.debug: 'true'   

variables:
  azureSubscription: 'edureka-rg-dev-SCN'  # serviceconnectiondetails
  appName: 'rmbchatbotapi'  # Name of your Azure App Service
  resourceGroup: 'edureka-rg-dev'  # Your resource group name
  packagePath: '$(System.DefaultWorkingDirectory)/app.zip'  # Path to the zip 
  


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    echo "Setting up Python environment..."
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
  displayName: 'Install Dependencies'



- script: |
    echo "Packaging Application..."
    zip -r app.zip .  # Zip the entire application
  displayName: 'Package Application'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    publishLocation: 'pipeline'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webAppLinux'
    appName: '$(appName)'
    package: '$(packagePath)'  # Path to the zipped application
  displayName: 'Deploy to Azure App Service'
